jboss-qa:
  image: adejonge/jbossas:latest
  ports:
   - "8081:8081"
jboss-pr:
  image: adejonge/jbossas:latest
  ports:
   - "8082:8081"
mocha:
  image: adejonge/mocha:latest
  links:
  - jboss-qa
  - jboss-pr
  command: "/usr/sbin/sshd -D"
xld:
  image: adejonge/xld:latest
  ports:
   - "4516:4516"
  links:
  - jboss-qa
  - jboss-pr
xlr:
  image: adejonge/xlr:latest
  ports:
   - "5516:5516"
  links:
  - jboss-qa
  - jboss-pr
  - mocha
  - xld
jenkins:
  image: jenkins:1.609.3
  ports:
   - "8080:8080"
  links:
  - xld
  - xlr
xlr:
  image: adejonge/xlr:latest
  ports:
   - "5516:5516"
  links:
  - jboss-qa
  - jboss-pr
  - mocha
  - xld
all:
  image: adejonge/training-proxy:latest
  ports:
   - "80:80"
  links:
  - jboss-qa
  - jboss-pr
  - mocha
  - xld
  - xlr
  - jenkins
